apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-database
  template:
    metadata:
      labels:
        app: ai-database
    spec:
      containers:
        - name: ai-database
          image: pgvector/pgvector:pg16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: ai-database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ai-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ai-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ai-database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ai-database
spec:
  selector:
    app: ai-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
