apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qdrant.fullname" . }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "qdrant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qdrant.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: qdrant
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: qdrant
              containerPort: 6333
              protocol: TCP
            - name: grpc
              containerPort: 6334
              protocol: TCP
          env:
          {{- if .Values.qdrant.enableAuth }}
            - name: QDRANT__ENABLE_AUTH
              value: "true"
            - name: QDRANT__API_KEY
              valueFrom:
              secretKeyRef:
                name: {{ .Values.qdrant.apiKeySecretName }}
                key: {{ .Values.qdrant.apiKeySecretKey }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: qdrant-data
              mountPath: /var/lib/qdrant/data
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: qdrant-data
          persistentVolumeClaim:
            claimName: {{ include "qdrant.fullname" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
