apiVersion: apps/v1
kind: Deployment
metadata:
  name: extension-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extension-service
  template:
    metadata:
      labels:
        app: extension-service
    spec:
      containers:
        - name: extension-service
          image: aagent.azurecr.io/extension-service:stg
          ports:
            - containerPort: 15300
          env:
            - name: NODE_ENV
              value: dev
            - name: PORT
              value: "15300"
            - name: COMPOSIO_API_BASE_URL
              value: https://backend.composio.dev/api
            - name: COMPOSIO_API_KEY
              value: d04n821zcnqtop53g98fx
            - name: DATABASE_URL
              value: mongodb://localhost:27017/datn-extension-database
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: extension-service
spec:
  selector:
    app: extension-service
  ports:
    - protocol: TCP
      port: 15300
      targetPort: 15300
