services:

  ####################################################
  ############### Services ###########################
  ####################################################
  user-service:
    env_file: ./user-service/.env
    ports:
      - "8100:8100"

  log-service:
    env_file: ./log-service/.env
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    ports:
      - "8200:8200"

  api-gateway:
    env_file: ./api-gateway/.env
    environment:
      NODE_ENV: production
      USER_SERVICE_URL: http://user-service:8100
      LOG_SERVICE_URL: http://log-service:8200
      RABBITMQ_URL: amqp://myuser:mypassword@rabbitmq:5672
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "8300:8300"

  ai-service:
    env_file: ./ai-service/.env
    environment:
      - POSTGRES_HOST=ai-database
      - POSTGRES_PORT=5432
    ports:
      - "5001:5001"

  ####################################################
  ################ Databases #########################
  ####################################################

  ai-database:
    healthcheck:
      test: pg_isready -U $POSTGRES_USER
      start_interval: 1s
      start_period: 5s
      interval: 5s
      retries: 5
    environment:
      - POSTGRES_DB=ai-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=ai-database
      - POSTGRES_PORT=5432
    ports:
      - "5433:5432"
    volumes:
      - ai-database:/var/lib/postgresql/data

  migration:
    depends_on:
      ai-database:
        condition: service_healthy
    environment:
      - POSTGRES_URL=postgres://postgres:123456@ai-database:5432/ai-database?sslmode=disable

  ####################################################
  ############### Extensions #########################
  ####################################################

  elasticsearch:
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - logstash_data:/usr/share/logstash/data

  kibana:
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      SERVER_NAME: "kibana"
      XPACK_SECURITY_ENABLED: "false"
    ports:
      - "5601:5601"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
      RABBITMQ_PLUGINS: rabbitmq_prometheus
