# Infrastructure Services Secrets
# This file contains secrets for core infrastructure services like Redis, RabbitMQ, and Elasticsearch

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default
type: Opaque
stringData:
  REDIS_PASSWORD: "root"
  REDIS_USER: "root"

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: default
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "root"
  RABBITMQ_DEFAULT_PASS: "root"

---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: default
type: Opaque
stringData:
  ELASTIC_PASSWORD: "elastic"
  ELASTICSEARCH_USERNAME: "elastic"
