{{- if and .Values.databases.extensionDatabase.enabled (not .Values.external.extensionDatabase.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "action-agent.fullname" . }}-extension-db-init
  namespace: {{ .Values.global.namespace }}
data:
  create-user.js: |
    db = db.getSiblingDB("{{ .Values.databases.extensionDatabase.database }}");
    db.createUser({
      user:   "{{ .Values.databases.extensionDatabase.auth.username }}",
      pwd:    "{{ .Values.databases.extensionDatabase.auth.password }}",
      roles:  [{ role: "readWrite", db: "{{ .Values.databases.extensionDatabase.database }}" }]
    });
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "action-agent.fullname" . }}-extension-db
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: extension-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "action-agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: extension-db
  template:
    metadata:
      labels:
        {{- include "action-agent.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: extension-db
    spec:
      securityContext:
        {{- toYaml .Values.databases.extensionDatabase.podSecurityContext | nindent 8 }}
      containers:
        - name: extension-db
          securityContext:
            {{- toYaml .Values.databases.extensionDatabase.securityContext | nindent 12 }}
          image: "{{ .Values.databases.extensionDatabase.image.repository }}:{{ .Values.databases.extensionDatabase.image.tag }}"
          imagePullPolicy: {{ .Values.databases.extensionDatabase.image.pullPolicy }}
          ports:
            - name: extension-db
              containerPort: {{ .Values.databases.extensionDatabase.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.databases.extensionDatabase.resources | nindent 12 }}
          volumeMounts:
            - name: extension-db-init
              mountPath: /docker-entrypoint-initdb.d/create-user.js
              subPath: create-user.js
            {{- if .Values.databases.extensionDatabase.persistence.enabled }}
            - name: extension-db-data
              mountPath: /data/db
            {{- end }}
          livenessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: extension-db-init
          configMap:
            name: {{ include "action-agent.fullname" . }}-extension-db-init
        {{- if .Values.databases.extensionDatabase.persistence.enabled }}
        - name: extension-db-data
          persistentVolumeClaim:
            claimName: {{ include "action-agent.fullname" . }}-extension-db-pvc
        {{- end }}
      {{- with .Values.databases.extensionDatabase.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.databases.extensionDatabase.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.databases.extensionDatabase.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- if .Values.databases.extensionDatabase.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "action-agent.fullname" . }}-extension-db-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: extension-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.databases.extensionDatabase.persistence.size }}
  {{- if .Values.databases.extensionDatabase.persistence.storageClass }}
  storageClassName: {{ .Values.databases.extensionDatabase.persistence.storageClass }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "action-agent.fullname" . }}-extension-db
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: extension-db
spec:
  type: ClusterIP
  ports:
    - name: extension-db
      port: {{ .Values.databases.extensionDatabase.service.port }}
      targetPort: extension-db
      protocol: TCP
  selector:
    {{- include "action-agent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: extension-db
{{- end }}
