{{- if .Values.elasticsearch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "action-agent.fullname" . }}-elasticsearch
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ include "action-agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
          ports:
            - containerPort: {{ .Values.elasticsearch.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "action-agent.fullname" . }}-elasticsearch
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ include "action-agent.labels" . | nindent 4 }}
spec:
  selector:
    app: elasticsearch
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      targetPort: {{ .Values.elasticsearch.service.port }}
{{- end }}
