{{- if .Values.elasticsearch.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aa.fullname" . }}-elasticsearch
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aa.labels" . | nindent 6 }}
      component: elasticsearch
  template:
    metadata:
      labels:
        {{- include "aa.labels" . | nindent 8 }}
        component: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: {{ include "aa.image" (dict "root" . "image" .Values.elasticsearch.image) }}
          env:
            - name: discovery.type
              value: {{ .Values.elasticsearch.env.discoveryType | quote }}
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.env.javaOpts | quote }}
            - name: xpack.security.enabled
              value: {{ .Values.elasticsearch.env.xpackSecurityEnabled | quote }}
          ports:
            - containerPort: {{ .Values.elasticsearch.service.port }}
              name: http
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aa.fullname" . }}-elasticsearch
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: elasticsearch
spec:
  type: ClusterIP
  selector:
    {{- include "aa.labels" . | nindent 4 }}
    component: elasticsearch
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      targetPort: {{ .Values.elasticsearch.service.port }}
      name: http
{{- end }}
