{{- if .Values.kibana.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aa.fullname" . }}-kibana
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aa.labels" . | nindent 6 }}
      component: kibana
  template:
    metadata:
      labels:
        {{- include "aa.labels" . | nindent 8 }}
        component: kibana
    spec:
      containers:
        - name: kibana
          image: {{ include "aa.image" (dict "root" . "image" .Values.kibana.image) }}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.kibana.env.elasticsearchHosts | quote }}
          ports:
            - containerPort: {{ .Values.kibana.service.port }}
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aa.fullname" . }}-kibana
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: kibana
spec:
  type: ClusterIP
  selector:
    {{- include "aa.labels" . | nindent 4 }}
    component: kibana
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.port }}
      name: http
{{- end }}
