{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "action-agent.fullname" . }}-rabbitmq
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ include "action-agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
          ports:
            - containerPort: {{ .Values.rabbitmq.service.port }}
            - containerPort: {{ .Values.rabbitmq.service.managementPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "action-agent.fullname" . }}-rabbitmq
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ include "action-agent.labels" . | nindent 4 }}
spec:
  selector:
    app: rabbitmq
  ports:
    - port: {{ .Values.rabbitmq.service.port }}
      targetPort: {{ .Values.rabbitmq.service.port }}
    - port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.rabbitmq.service.managementPort }}
{{- end }}
