{{- if .Values.rabbitmq.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aa.fullname" . }}-rabbitmq
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aa.labels" . | nindent 6 }}
      component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "aa.labels" . | nindent 8 }}
        component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ include "aa.image" (dict "root" . "image" .Values.rabbitmq.image) }}
          ports:
            - containerPort: {{ .Values.rabbitmq.service.port }}
              name: amqp
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aa.fullname" . }}-rabbitmq
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: rabbitmq
spec:
  type: ClusterIP
  selector:
    {{- include "aa.labels" . | nindent 4 }}
    component: rabbitmq
  ports:
    - port: {{ .Values.rabbitmq.service.port }}
      targetPort: {{ .Values.rabbitmq.service.port }}
      name: amqp
{{- end }}
