{{- if .Values.redis.enabled }}
{{- if .Values.redis.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aa.fullname" . }}-redis-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aa.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aa.labels" . | nindent 6 }}
      component: redis
  template:
    metadata:
      labels:
        {{- include "aa.labels" . | nindent 8 }}
        component: redis
    spec:
      containers:
        - name: redis
          image: {{ include "aa.image" (dict "root" . "image" .Values.redis.image) }}
          ports:
            - containerPort: {{ .Values.redis.service.port }}
              name: redis
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - mountPath: /data
              name: data
          {{- end }}
      {{- if .Values.redis.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "aa.fullname" . }}-redis-pvc
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aa.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "aa.labels" . | nindent 4 }}
    component: redis
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      name: redis
{{- end }}
