{{- if .Values.redis.enabled }}

#---------------------------------------
# ConfigMap – host/port for app pods
#---------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "action-agent.fullname" . }}-redis-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ include "action-agent.fullname" . }}-redis
  REDIS_PORT: {{ .Values.redis.service.port | quote }}

#---------------------------------------
# Deployment
#---------------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "action-agent.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "action-agent.selectorLabels" . | nindent 6 }}
      app: redis
  template:
    metadata:
      labels:
        {{- include "action-agent.selectorLabels" . | nindent 8 }}
        app: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "action-agent.fullname" . }}-redis-config
            {{- if .Values.secrets.createSecrets }}
            - secretRef:
                name: {{ include "action-agent.fullname" . }}-infrastructure-secret
            {{- end }}
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          {{- end }}
          resources:
            limits:   { cpu: 500m, memory: 512Mi }
            requests: { cpu: 100m, memory: 128Mi }
      volumes:
        - name: redis-data
          {{- if .Values.redis.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "action-agent.fullname" . }}-redis-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}

# PVC only when persistence on
{{- if .Values.redis.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "action-agent.fullname" . }}-redis-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}

#---------------------------------------
# Service
#---------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "action-agent.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP        # always internal
  selector:
    {{- include "action-agent.selectorLabels" . | nindent 4 }}
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}

{{- end }}