# Example Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: action-agent-be-secrets
  labels:
    app: action-agent-be
type: Opaque
data:
  EMAIL_PASSWORD: "bXlhaWFzc2lzdGFudDI0QGdtYWlsLmNvbQ=="
  JWT_SECRET: ""  # Add your JWT secret, base64-encoded
  LLM_DEFAULT_API_KEY: "c2stcHJvai1YT25vWDFGT1FaMXJLWExVRTFoOGV0MjFwaTFHZHJiVWdjMkpwNk1RUXlBVW9jN2hNQTBBVlJ4RDJWR1lWU0VzdlFGMzBUT1QybVR3QmxiRkpMZ3pvaXZ4cFR2SEU1THMxWDhweFgyTW1ILUUyUllDNHZIUldTbzViSTBFdzl2ZGdsaE9JN29QblpjbjdHQ3lEN0syMG9xQTZwRUE="
  TOOL_TAVILY_API_KEY: "dmxseS1kZXYtVTNMS2ZqUHl5bUtsWTZZbkM3bHE4UWtsOHM1QXpnZDQ="
  COMPOSIO_API_KEY: "ZDA0bjgyMXpjbnF0b3A1M2c5OGZ4"
