# Default values for aiservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: myaagent.azurecr.io/aiservicestg
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: BuildID

nameOverride: "aiservicestg"
fullnameOverride: "aiservicestg"

env:
  - name: DEBUG_SERVER
    value: "False"
  
  - name: DEBUG_SQLALCHEMY
    value: "False"

  - name: LOGGING_LOG_LEVEL
    value: "INFO"

  - name: POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: posgresqlhost
  - name: POSTGRES_PORT
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: postgresqlport
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: postgresqluser
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: postgresqlpassword
  - name: POSTGRES_DB
    value: "aiservicestg"

  - name: LLM_DEFAULT_PROVIDER
    value: "openai"

  - name: LLM_DEFAULT_MODEL
    value: "gpt-4o-mini"

  - name: LLM_DEFAULT_API_KEY
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: openaiapikey

  - name: TOOL_TAVILY_API_KEY
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: taviliapikey

  - name: COMPOSIO_LOGGING_LEVEL
    value: "debug"
  - name: COMPOSIO_API_KEY
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: composioapikey
  - name: COMPOSIO_REDIRECT_URL
    value: "https://api-stg.action-agent.software/ai/api/v1/callback/extension"
  - name: FRONTEND_REDIRECT_URL
    value: "https://stg.action-agent.software/callback/extension"
  
  - name: ELASTICSEARCH_URL
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: elasticsearchurl
  - name: REDIS_URL
    value: "redis://redisstg:6379"
  
  - name: RABBITMQ_URL
    value: "amqp://rabbitmqstg:5672"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    spec.ingressClassName: "nginx"
    nginx.org/websocket-services: "aiservicestg"
    nginx.ingress.kubernetes.io/client-max-body-size: "30m"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: ai-stg.action-agent.software
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: aiservicestg
              port:
                number: 15000
  tls:
    - secretName: aiservice-stg-tls
      hosts:
        - ai-stg.action-agent.software