# Default values for apigateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: myaagent.azurecr.io/apigatewaystg
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: BuildID

nameOverride: "apigatewaystg"
fullnameOverride: "apigatewaystg"

env:
  - name: PORT
    value: "15000"

  - name: NODE_ENV
    value: "stg"

  - name: ELASTICSEARCH_URL
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: elasticsearchurl

  - name: RABBITMQ_URL
    value: "amqp://rabbitmqstg:5672"

  - name: REDIS_URL
    value: "redis://redisstg:6379"

  - name: USER_SERVICE_URL
    value: "http://userservicestg:15100"

  - name: AI_SERVICE_URL
    value: "aiservicestg:15200"

  - name: EXTENSION_SERVICE_URL
    value: "extensionservicestg:15300"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    spec.ingressClassName: "nginx"
    nginx.org/websocket-services: "apigatewaystg"
    nginx.ingress.kubernetes.io/client-max-body-size: "30m"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: api-stg.action-agent.software
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: apigatewaystg
              port:
                number: 15000
  tls:
    - secretName: apigateway-stg-tls
      hosts:
        - api-stg.action-agent.software
