apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.**>
      @type record_modifier
      <record>
        namespace_name ${record["kubernetes"]["namespace_name"]}
      </record>
    </filter>

    <match kubernetes.**>
      @type copy

      <store>
        @type elasticsearch
        @id es_dev
        <match>
          namespace_name dev
        </match>
        host "#{ENV['ELASTICSEARCH_DEV_HOST']}"
        port 443
        scheme https
        user "#{ENV['ELASTICSEARCH_DEV_USER']}"
        password "#{ENV['ELASTICSEARCH_DEV_PASS']}"
        logstash_format true
        include_tag_key true
        type_name fluentd
        flush_interval 5s
        <buffer tag>
          @type file
          path /fluentd/buffer/dev
          flush_thread_count 2
          retry_forever true
        </buffer>
      </store>

      <store>
        @type elasticsearch
        @id es_stg
        <match>
          namespace_name stg
        </match>
        host "#{ENV['ELASTICSEARCH_STG_HOST']}"
        port 443
        scheme https
        user "#{ENV['ELASTICSEARCH_STG_USER']}"
        password "#{ENV['ELASTICSEARCH_STG_PASS']}"
        logstash_format true
        include_tag_key true
        type_name fluentd
        flush_interval 5s
        <buffer tag>
          @type file
          path /fluentd/buffer/stg
          flush_thread_count 2
          retry_forever true
        </buffer>
      </store>

      <store>
        @type elasticsearch
        @id es_prod
        <match>
          namespace_name prod
        </match>
        host "#{ENV['ELASTICSEARCH_PROD_HOST']}"
        port 443
        scheme https
        user "#{ENV['ELASTICSEARCH_PROD_USER']}"
        password "#{ENV['ELASTICSEARCH_PROD_PASS']}"
        logstash_format true
        include_tag_key true
        type_name fluentd
        flush_interval 5s
        <buffer tag>
          @type file
          path /fluentd/buffer/prod
          flush_thread_count 2
          retry_forever true
        </buffer>
      </store>
    </match>
