apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-database-config
  namespace: default
data:
  POSTGRES_DB: "ai-database"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "123456"
  POSTGRES_HOST: "ai-database"
  POSTGRES_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-database
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-database
  template:
    metadata:
      labels:
        app: ai-database
    spec:
      containers:
        - name: ai-database
          image: pgvector/pgvector:pg16
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: ai-database-config
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ai-database
  namespace: default
spec:
  selector:
    app: ai-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
