apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-service-config
  namespace: default
data:
  DEBUG_AGENT: "False"
  DEBUG_SERVER: "False"
  DEBUG_SQLALCHEMY: "False"
  LOGGING_LOG_LEVEL: "INFO"
  LLM_DEFAULT_PROVIDER: "openai"
  LLM_DEFAULT_MODEL: "gpt-4o-mini"
  LLM_DEFAULT_API_KEY: "<YOUR_OPENAI_API_KEY>"
  POSTGRES_HOST: "ai-database"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "123456"
  POSTGRES_DB: "ai-database"
  TOOL_TAVILY_API_KEY: "<YOUR_TAVILY_API_KEY>"
  COMPOSIO_LOGGING_LEVEL: "debug"
  COMPOSIO_API_KEY: "<YOUR_COMPOSIO_API_KEY>"
  COMPOSIO_REDIRECT_URL: "https://localhost:15000/ai/api/v1/callback/extension"
  FRONTEND_REDIRECT_URL: "http://localhost:3000/callback/extension"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: aagent.azurecr.io/ai-service:stg
          ports:
            - containerPort: 15200
          envFrom:
            - configMapRef:
                name: ai-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: default
spec:
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 15200
      targetPort: 15200
