apiVersion: v1
kind: ConfigMap
metadata:
  name: extension-database-config
  namespace: default
data:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "root"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extension-database
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extension-database
  template:
    metadata:
      labels:
        app: extension-database
    spec:
      containers:
        - name: extension-database
          image: mongo:latest
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: extension-database-config
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: extension-database
  namespace: default
spec:
  selector:
    app: extension-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

