apiVersion: v1
kind: ConfigMap
metadata:
  name: extension-service-config
  namespace: default
data:
  NODE_ENV: "dev"
  PORT: "15300"
  COMPOSIO_API_BASE_URL: "https://backend.composio.dev/api"
  COMPOSIO_API_KEY: "d04n821zcnqtop53g98fx"
  DATABASE_URL: "mongodb://root:root@extension-database:27017/datn-extension-database?authSource=admin"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extension-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extension-service
  template:
    metadata:
      labels:
        app: extension-service
    spec:
      containers:
        - name: extension-service
          image: aagent.azurecr.io/extension-service:stg
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 15300
          envFrom:
            - configMapRef:
                name: extension-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: extension-service
  namespace: default
spec:
  selector:
    app: extension-service
  ports:
    - protocol: TCP
      port: 15300
      targetPort: 15300
