# Default values for paymentservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: myaagent.azurecr.io/paymentservicedev
  pullPolicy: Always
  tag: BuildID

nameOverride: "paymentservicedev"
fullnameOverride: "paymentservicedev"

env:
  - name: Logging__LogLevel__Default
    value: "Information"
  - name: Logging__LogLevel__Microsoft.AspNetCore
    value: "Warning"

  - name: AllowedHosts
    value: "*"

  - name: ASPNETCORE_HTTP_PORTS
    value: "15700"

  - name: MongoSettings__ConnectionString
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: mongodbconnectionstring
  - name: MongoSettings__DatabaseName
    value: "test"
  - name: MongoSettings__UserCollectionName
    value: "Users"
  - name: MongoSettings__PaymentCollectionName
    value: "Payments"

  - name: StripeSettings__SecretKey
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: stripesecretkey
  - name: StripeSettings__WebhookSecret
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: stripewebhooksecret

  - name: RateSettings__CreditsPerUsd
    value: "1000000"

ingress:
  enabled: false