# Default values for paymentservice.
image:
  repository: myaagent.azurecr.io/paymentserviceprod
  pullPolicy: Always
  tag: BuildID

nameOverride: "paymentserviceprod"
fullnameOverride: "paymentserviceprod"

env:
  - name: Logging__LogLevel__Default
    value: "Information"
  - name: Logging__LogLevel__Microsoft.AspNetCore
    value: "Warning"

  - name: AllowedHosts
    value: "*"

  - name: ASPNETCORE_HTTP_PORTS
    value: "15700"

  - name: MongoSettings__ConnectionString
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: mongodbconnectionstring
  - name: MongoSettings__DatabaseName
    value: "user-service"
  - name: MongoSettings__UserCollectionName
    value: "Users"
  - name: MongoSettings__PaymentCollectionName
    value: "Payments"

  - name: StripeSettings__SecretKey
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: stripesecretkey
  - name: StripeSettings__WebhookSecret
    valueFrom:
      secretKeyRef:
        name: env-secret
        key: stripewebhooksecret

  - name: RateSettings__CreditsPerUsd
    value: "1000000"

ingress:
  enabled: false