apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-database
  template:
    metadata:
      labels:
        app: user-database
    spec:
      containers:
        - name: user-database
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: user-database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-database
spec:
  selector:
    app: user-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
