apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: default
data:
  ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  SERVER_NAME: "kibana"
  XPACK_SECURITY_ENABLED: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.16.1
          ports:
            - containerPort: 5601
          envFrom:
            - configMapRef:
                name: kibana-config
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
