apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: aagent.azurecr.io/api-gateway:stg
          ports:
            - containerPort: 15000
          env:
            - name: HTTPS_PORT
              value: "15000"
            - name: USER_SERVICE_URL
              value: http://user-service:15100
            - name: AI_SERVICE_URL
              value: http://ai-service:15200
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: RABBITMQ_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: REDIS_URL
            - name: MICROSERVICE_TIMEOUT
              value: "300000"
          volumeMounts:
            - name: certs
              mountPath: /usr/src/app/certs
              readOnly: true
      volumes:
        - name: certs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 15000
      targetPort: 15000
