# =====================================================================
#  Global defaults (do not change per-environment here)
# =====================================================================
global:
  imageRegistry: ""          # overridden per env
  environment: ""            # dev | stg | prod
  namespace: ""              # release namespace

image:
  pullPolicy: IfNotPresent
  pullSecrets: []            # registry secret names per env

serviceAccount:
  create: true
  annotations: {}
  name: ""

# ---------------------------------------------------------------------
# Infrastructure – OFF by default (each env enables what it needs)
# ---------------------------------------------------------------------
redis:
  enabled: false
  auth:
    password: ""  # Will be overridden in environment-specific values files

rabbitmq:
  enabled: false
  auth:
    username: ""  # Will be overridden in environment-specific values files
    password: ""  # Will be overridden in environment-specific values files

elasticsearch:
  enabled: false
  auth:
    username: ""  # Will be overridden in environment-specific values files
    password: ""  # Will be overridden in environment-specific values files

kibana:
  enabled: false

# ---------------------------------------------------------------------
# Micro-services (image.tag & resources overridden per env)
# ---------------------------------------------------------------------
apiGateway:
  enabled: true
  replicaCount: 1
  image:
    repository: api-gateway
    tag: ""
  service:
    type: ClusterIP
    port: 15000
  ssl:
    enabled: true
    keyPath: /app/certs/key.pem
    certPath: /app/certs/cert.pem
  resources:
    requests: { cpu: 50m,  memory: 64Mi }
    limits:   { cpu: 250m, memory: 256Mi }

userService:
  enabled: true
  replicaCount: 1
  image:
    repository: user-service
    tag: ""
  service:
    type: ClusterIP
    port: 15100
  database:
    enabled: false
  resources:
    requests: { cpu: 50m,  memory: 128Mi }
    limits:   { cpu: 250m, memory: 256Mi }

aiService:
  enabled: true
  replicaCount: 1
  image:
    repository: ai-service
    tag: ""
  service:
    type: ClusterIP
    port: 15200
  database:
    enabled: false
  resources:
    requests: { cpu: 100m, memory: 256Mi }
    limits:   { cpu: 500m, memory: 512Mi }

extensionService:
  enabled: true
  replicaCount: 1
  image:
    repository: extension-service
    tag: ""
  service:
    type: ClusterIP
    port: 15300
  database:
    enabled: false
  resources:
    requests: { cpu: 50m,  memory: 128Mi }
    limits:   { cpu: 250m, memory: 256Mi }

# ---------------------------------------------------------------------
# Secret strategy – overriden per env
# ---------------------------------------------------------------------
secrets:
  createSecrets: true        # dev uses local env-files
  external:
    provider: ""             # azure-keyvault for stg/prod
    secretStore: ""

# Config values
config:
  jwt:
    secret: ""  # Will be overridden in environment-specific values files
  composio:
    apiKey: ""  # Will be overridden in environment-specific values files
    apiBaseUrl: ""  # Will be overridden in environment-specific values files
  microserviceTimeout: "5000"  # Default timeout in milliseconds
  email:
    username: ""  # Will be overridden in environment-specific values files
    password: ""  # Will be overridden in environment-specific values files

# External services configuration
externalServices:
  mongoUrl: ""  # Will be overridden in environment-specific values files

ingress: { enabled: false }
autoscaling: { enabled: false }
nodeSelector: {}
tolerations: []
affinity: {}
