# Staging environment values
global:
  environment: stg
  namespace: action-agent-stg

# Infrastructure - Use managed services in staging
redis:
  enabled: true
  persistence:
    enabled: true
    size: 2Gi

rabbitmq:
  enabled: true
  persistence:
    enabled: true
    size: 2Gi

elasticsearch:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
  config:
    javaOpts: "-Xms1g -Xmx1g"

# Application Services - Higher resources for staging
apiGateway:
  replicaCount: 2
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

userService:
  replicaCount: 2
  database:
    persistence:
      enabled: true
      size: 5Gi
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

aiService:
  replicaCount: 2
  database:
    persistence:
      enabled: true
      size: 10Gi
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi

extensionService:
  replicaCount: 2
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Secret Management - Use external secrets in staging
secrets:
  createSecrets: false
  external:
    provider: "external-secrets"
    secretStore: "staging-secret-store"

# Ingress
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: stg-api.action-agent.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: action-agent-stg-tls
      hosts:
        - stg-api.action-agent.com

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
