secretProvider: local

localSecrets:
  api-gateway-secret:
    HTTPS_PORT: "15000"
    USER_SERVICE_URL: http://user-service:15100
    AI_SERVICE_URL: http://ai-service:15200
    ELASTICSEARCH_URL: http://elasticsearch:9200
    RABBITMQ_URL: amqp://root:root@rabbitmq:5672
    REDIS_URL: redis://redis:6379
  user-service-secret:
    MONGODB_CONNECTION_STRING: mongodb://root:root@mongo:27017/user-service?authSource=admin
    JWT_SECRET: dev-secret
  ai-service-secret:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: "5432"
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: ai-database
  extension-service-secret:
    DATABASE_URL: mongodb://root:root@mongo:27017/datn-extension-database?authSource=admin

elasticsearch:
  enabled: true
kibana:
  enabled: true
rabbitmq:
  enabled: true
