global:
  namespace: default
  imageRegistry: ""
  environment: dev

secretProvider: local

secrets:
  apiGateway: api-gateway-secret
  userService: user-service-secret
  aiService: ai-service-secret
  extensionService: extension-service-secret

# localSecrets and externalSecrets are defined per environment

apiGateway:
  enabled: true
  replicaCount: 1
  image:
    repository: api-gateway
    tag: latest
  service:
    type: ClusterIP
    port: 15000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

userService:
  enabled: true
  replicaCount: 1
  image:
    repository: user-service
    tag: latest
  service:
    type: ClusterIP
    port: 15100
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

aiService:
  enabled: true
  replicaCount: 1
  image:
    repository: ai-service
    tag: latest
  service:
    type: ClusterIP
    port: 15200
  resources:
    limits:
      cpu: 750m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

extensionService:
  enabled: true
  replicaCount: 1
  image:
    repository: extension-service
    tag: latest
  service:
    type: ClusterIP
    port: 15300
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "16"
  service:
    type: ClusterIP
    port: 5432
  auth:
    username: postgres
    password: postgres
    database: ai-database
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

mongo:
  enabled: true
  image:
    repository: mongo
    tag: latest
  service:
    type: ClusterIP
    port: 27017
  auth:
    username: root
    password: root
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

redis:
  enabled: true
  image:
    repository: redis
    tag: latest
  service:
    port: 6379
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

elasticsearch:
  enabled: false
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 8.16.1
  service:
    port: 9200
  env:
    discoveryType: single-node
    javaOpts: -Xms512m -Xmx512m
    xpackSecurityEnabled: "false"

kibana:
  enabled: false
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: 8.16.1
  service:
    port: 5601
  env:
    elasticsearchHosts: http://elasticsearch:9200

rabbitmq:
  enabled: false
  image:
    repository: rabbitmq
    tag: 3-management
  service:
    port: 5672
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
