global:
  namespace: default
  imageRegistry: ""

secretProvider: local

secrets:
  apiGateway: api-gateway
  userService: user-service
  aiService: ai-service
  extensionService: extension-service
  databases: databases
  infrastructure: infrastructure

apiGateway:
  enabled: true
  replicaCount: 1
  image:
    repository: api-gateway
    tag: latest
  service:
    port: 15000
    type: ClusterIP

userService:
  enabled: true
  replicaCount: 1
  image:
    repository: user-service
    tag: latest
  service:
    port: 15100
    type: ClusterIP
  database:
    name: user-service
    username: root
    password: root
    image:
      repository: mongo
      tag: latest
    persistence:
      enabled: true
      size: 1Gi

aiService:
  enabled: true
  replicaCount: 1
  image:
    repository: ai-service
    tag: latest
  service:
    port: 15200
    type: ClusterIP
  database:
    name: ai-database
    username: postgres
    password: "123456"
    image:
      repository: pgvector/pgvector
      tag: pg16
    persistence:
      enabled: true
      size: 1Gi

extensionService:
  enabled: true
  replicaCount: 1
  image:
    repository: extension-service
    tag: latest
  service:
    port: 15300
    type: ClusterIP

redis:
  enabled: true
  image:
    repository: redis
    tag: latest
  service:
    port: 6379
  persistence:
    enabled: true
    size: 1Gi

elasticsearch:
  enabled: false
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 8.16.1
  service:
    port: 9200
  persistence:
    enabled: true
    size: 2Gi

kibana:
  enabled: false
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: 8.16.1
  service:
    port: 5601

rabbitmq:
  enabled: false
  image:
    repository: rabbitmq
    tag: 3-management
  service:
    port: 5672
    managementPort: 15672
  persistence:
    enabled: true
    size: 1Gi
