# =========================================================
#  Production values  (AKS)  —  databases run as pods
# =========================================================
global:
  environment: prod
  namespace: action-agent-prod
  imageRegistry: aagent.azurecr.io

image:
  pullSecrets: [acr-pull]

# ---------------------------------------------------------
# Infrastructure
# ---------------------------------------------------------
redis:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi

rabbitmq:
  enabled: false

elasticsearch:
  enabled: false

kibana:
  enabled: false

externalServices:
  rabbitmqUrl:  amqps://user:pass@vhost.lil.cloudamqp.com/vhost
  elasticUrl:   https://abcd.bonsaisearch.net

# ---------------------------------------------------------
# Micro-services
# ---------------------------------------------------------
apiGateway:
  replicaCount: 1
  resources:
    requests: { cpu: 256m, memory: 256Mi }
    limits:   { cpu: 1000m, memory: 1Gi }

userService:
  replicaCount: 1
  database:
    enabled: true
    image:
      repository: mongo
      tag: "latest"
    username: root
    password: root
    persistence:
      enabled: true
      size: 1Gi
  resources:
    requests: { cpu: 100m, memory: 100Mi }
    limits:   { cpu: 1000m, memory: 1Gi }

aiService:
  replicaCount: 2
  database:
    enabled: true
    image:
      repository: pgvector/pgvector
      tag: "pg16"
    username: postgres
    password: postgres
    persistence:
      enabled: true
      size: 1Gi
  resources:
    requests: { cpu: 256m, memory: 256Mi }
    limits:   { cpu: 1000m, memory: 1Gi }

extensionService:
  replicaCount: 2
  database:
    enabled: true
    image:
      repository: mongo
      tag: "latest"
    username: root
    password: root
    persistence:
      enabled: true
      size: 1Gi
  resources:
    requests: { cpu: 100m, memory: 100Mi }
    limits:   { cpu: 1000m, memory: 1Gi }

# ---------------------------------------------------------
# Secrets — still via Key Vault for API keys, but DB creds
# are created as in-cluster Secrets by the chart.
# ---------------------------------------------------------
secrets:
  createSecrets: true        # chart will create DB secrets
  external:
    provider: azure-keyvault
    secretStore: action-agent-kv

# ---------------------------------------------------------
# Ingress & autoscaling stay unchanged
# ---------------------------------------------------------
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.action-agent.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: action-agent-prod-tls
      hosts: [api.action-agent.com]

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
