# Default values for rabbitmq
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "rabbitmqprod"
fullnameOverride: "rabbitmqprod"

image:
  repository: rabbitmq
  tag: 3-management
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  amqpPort: 5672
  managementPort: 15672

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi

rabbitmq:
  username: "guest"
  password: "guest"
  erlangCookie: "SWQOKODSQALRPCLNMEQG"

management:
  enabled: true

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
