# Default values for rabbitmq
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "rabbitmqstg"
fullnameOverride: "rabbitmqstg"

image:
  repository: rabbitmq
  tag: 3-management
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  amqpPort: 5672
  managementPort: 15672

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 2Gi

rabbitmq:
  username: "guest"
  password: "guest"
  erlangCookie: "SWQOKODSQALRPCLNMEQG"

management:
  enabled: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
