name: 'Docker Build and Push'
description: 'Build and push a Docker image to Azure Container Registry (ACR)'

inputs:
  acr_username:
    description: 'Azure Container Registry Username'
    required: true
  acr_password:
    description: 'Azure Container Registry Password'
    required: true
  image_name:
    description: 'The name of the Docker image'
    required: true
  tag:
    description: 'The tag for the Docker image'
    required: true
  folder:
    description: 'The folder containing the Dockerfile and build context'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to ACR
      shell: bash
      run: echo "${{ inputs.acr_password }}" | docker login aagent.azurecr.io -u "${{ inputs.acr_username }}" --password-stdin

    - name: Build & Push Docker Image
      shell: bash
      run: |
        docker build -t aagent.azurecr.io/${{ inputs.image_name }}:${{ inputs.tag }} ${{ inputs.folder }}
        docker push aagent.azurecr.io/${{ inputs.image_name }}:${{ inputs.tag }}
