{{- if .Values.aiService.enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "action-agent.fullname" . }}-ai-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
    app: ai-service
spec:
  replicas: {{ .Values.aiService.replicaCount }}
  selector:
    matchLabels:
      {{- include "action-agent.selectorLabels" . | nindent 6 }}
      app: ai-service
  template:
    metadata:
      labels:
        {{- include "action-agent.selectorLabels" . | nindent 8 }}
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: {{ .Values.aiService.image.repository }}:{{ .Values.aiService.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.aiService.service.port }}
          env:
            - name: PORT
              value: {{ .Values.aiService.service.port | quote }}
          envFrom:
            {{- if .Values.secrets.createSecrets }}
            - secretRef:
                name: {{ include "action-agent.fullname" . }}-ai-service-secret
            {{- end }}
          resources:
            {{- toYaml .Values.aiService.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.aiService.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.aiService.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "action-agent.fullname" . }}-ai-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.aiService.service.type }}
  selector:
    {{- include "action-agent.selectorLabels" . | nindent 4 }}
    app: ai-service
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.aiService.service.port }}
      targetPort: {{ .Values.aiService.service.port }}
{{- end }}  {{/* END aiService.enabled */}}
