{{- if .Values.apiGateway.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aa.fullname" . }}-api-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "aa.labels" . | nindent 6 }}
      component: api-gateway
  template:
    metadata:
      labels:
        {{- include "aa.labels" . | nindent 8 }}
        component: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: {{ include "aa.image" (dict "root" . "image" .Values.apiGateway.image) }}
          ports:
            - containerPort: {{ .Values.apiGateway.service.port }}
              name: http
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.apiGateway }}
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aa.fullname" . }}-api-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  selector:
    {{- include "aa.labels" . | nindent 4 }}
    component: api-gateway
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.port }}
      name: http
{{- end }}
