{{- if .Values.apiGateway.enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "action-agent.fullname" . }}-api-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
    app: api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "action-agent.selectorLabels" . | nindent 6 }}
      app: api-gateway
  template:
    metadata:
      labels:
        {{- include "action-agent.selectorLabels" . | nindent 8 }}
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: {{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: {{ if .Values.apiGateway.ssl.enabled }}https{{ else }}http{{ end }}
              containerPort: {{ .Values.apiGateway.service.port }}
          env:
            - name: PORT
              value: {{ .Values.apiGateway.service.port | quote }}
          envFrom:
            {{- if .Values.secrets.createSecrets }}
            - secretRef:
                name: {{ include "action-agent.fullname" . }}-api-gateway-secret
            {{- else }}
            {{- if .Values.apiGateway.ssl.enabled }}
            - name: SSL_KEY_PATH
              value: {{ .Values.apiGateway.ssl.keyPath | quote }}
            - name: SSL_CERT_PATH
              value: {{ .Values.apiGateway.ssl.certPath | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
          # ---------- probes ----------
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.apiGateway.service.port }}
              scheme: {{ ternary "HTTPS" "HTTP" .Values.apiGateway.ssl.enabled }}
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.apiGateway.service.port }}
              scheme: {{ ternary "HTTPS" "HTTP" .Values.apiGateway.ssl.enabled }}
            initialDelaySeconds: 60
            periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "action-agent.fullname" . }}-api-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type | default "ClusterIP" }}
  selector:
    {{- include "action-agent.selectorLabels" . | nindent 4 }}
    app: api-gateway
  ports:
    - name: {{ if .Values.apiGateway.ssl.enabled }}https{{ else }}http{{ end }}
      protocol: TCP
      port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.port }}

{{- end }}  {{/* END apiGateway.enabled */}}
