{{- /*
-----------------------------------------------------------------
  EXTENSION-SERVICE ── OPTIONAL MONGO DATABASE
-----------------------------------------------------------------
*/ -}}
{{- if and .Values.extensionService.enabled .Values.extensionService.database.enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "action-agent.fullname" . }}-extension-database
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
    app: extension-database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "action-agent.selectorLabels" . | nindent 6 }}
      app: extension-database
  template:
    metadata:
      labels:
        {{- include "action-agent.selectorLabels" . | nindent 8 }}
        app: extension-database
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.extensionService.database.image.repository }}:{{ .Values.extensionService.database.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: mongo
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.extensionService.database.username | quote }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.extensionService.database.password | quote }}
          {{- if .Values.extensionService.database.persistence.enabled }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          {{- end }}
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
      {{- if .Values.extensionService.database.persistence.enabled }}
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: {{ include "action-agent.fullname" . }}-extension-database-pvc
      {{- else }}
      volumes:
        - name: mongo-data
          emptyDir: {}
      {{- end }}

{{- if .Values.extensionService.database.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "action-agent.fullname" . }}-extension-database-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.extensionService.database.persistence.size }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "action-agent.fullname" . }}-extension-database
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "action-agent.selectorLabels" . | nindent 4 }}
    app: extension-database
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017

{{- end }}   {{/* END database.enabled */}}

{{- /*
-----------------------------------------------------------------
  EXTENSION-SERVICE ── MAIN APP DEPLOYMENT
-----------------------------------------------------------------
*/ -}}
{{- if .Values.extensionService.enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "action-agent.fullname" . }}-extension-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
    app: extension-service
spec:
  replicas: {{ .Values.extensionService.replicaCount }}
  selector:
    matchLabels:
      {{- include "action-agent.selectorLabels" . | nindent 6 }}
      app: extension-service
  template:
    metadata:
      labels:
        {{- include "action-agent.selectorLabels" . | nindent 8 }}
        app: extension-service
    spec:
      containers:
        - name: extension-service
          image: {{ include "action-agent.image" (dict "root" . "image" .Values.extensionService.image) }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.extensionService.service.port }}
          env:
            - name: PORT
              value: {{ .Values.extensionService.service.port | quote }}
            {{- if not .Values.extensionService.database.enabled }}
            - name: DATABASE_URL
              value: {{ .Values.extensionService.database.url | quote }}
            {{- end }}
          envFrom:
            {{- if .Values.secrets.createSecrets }}
            - secretRef:
                name: {{ include "action-agent.secretName" (dict "root" . "name" "extension-service") }}
            {{- end }}
          resources:
            {{- toYaml .Values.extensionService.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.extensionService.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.extensionService.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "action-agent.fullname" . }}-extension-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.extensionService.service.type | default "ClusterIP" }}
  selector:
    {{- include "action-agent.selectorLabels" . | nindent 4 }}
    app: extension-service
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.extensionService.service.port }}
      targetPort: {{ .Values.extensionService.service.port }}

{{- end }}   {{/* END extensionService.enabled */}}
