{{- if .Values.extensionService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "action-agent.fullname" . }}-extension-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ include "action-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.extensionService.replicaCount }}
  selector:
    matchLabels:
      app: extension-service
  template:
    metadata:
      labels:
        app: extension-service
    spec:
      containers:
        - name: extension-service
          image: {{ include "action-agent.image" (dict "root" . "repository" .Values.extensionService.image.repository "tag" .Values.extensionService.image.tag) }}
          ports:
            - containerPort: {{ .Values.extensionService.service.port }}
          envFrom:
            - secretRef:
                name: {{ include "action-agent.secretName" (dict "root" . "name" .Values.secrets.extensionService) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "action-agent.fullname" . }}-extension-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ include "action-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.extensionService.service.type }}
  selector:
    app: extension-service
  ports:
    - port: {{ .Values.extensionService.service.port }}
      targetPort: {{ .Values.extensionService.service.port }}
{{- end }}
