{{- if .Values.userService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aa.fullname" . }}-user-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: user-service
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      {{- include "aa.labels" . | nindent 6 }}
      component: user-service
  template:
    metadata:
      labels:
        {{- include "aa.labels" . | nindent 8 }}
        component: user-service
    spec:
      containers:
        - name: user-service
          image: {{ include "aa.image" (dict "root" . "image" .Values.userService.image) }}
          ports:
            - containerPort: {{ .Values.userService.service.port }}
              name: http
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.userService }}
          resources:
            {{- toYaml .Values.userService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aa.fullname" . }}-user-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aa.labels" . | nindent 4 }}
    component: user-service
spec:
  type: {{ .Values.userService.service.type }}
  selector:
    {{- include "aa.labels" . | nindent 4 }}
    component: user-service
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: {{ .Values.userService.service.port }}
      name: http
{{- end }}
