{{- if .Values.secrets.createSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "action-agent.fullname" . }}-infrastructure-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Redis
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  REDIS_USER: {{ .Values.redis.auth.username | quote }}
  
  # RabbitMQ
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.auth.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.auth.password | quote }}
  
  # Elasticsearch
  ELASTIC_PASSWORD: {{ .Values.elasticsearch.auth.password | quote }}
  ELASTICSEARCH_USERNAME: {{ .Values.elasticsearch.auth.username | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "action-agent.fullname" . }}-application-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  # JWT Secret
  JWT_SECRET: {{ .Values.config.jwt.secret | quote }}
  
  # External API Keys
  COMPOSIO_API_KEY: {{ .Values.config.composio.apiKey | quote }}
  COMPOSIO_API_BASE_URL: {{ .Values.config.composio.apiBaseUrl | quote }}
  
  # Microservice timeout
  MICROSERVICE_TIMEOUT: {{ .Values.config.microserviceTimeout | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "action-agent.fullname" . }}-connections-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Service Connection URLs
  {{- if .Values.redis.enabled }}
  REDIS_URL: "redis://{{ include "action-agent.fullname" . }}-redis:{{ .Values.redis.service.port }}"
  {{- else }}
  REDIS_URL: "{{ .Values.config.externalRedisUrl }}"
  {{- end }}
  
  {{- if .Values.rabbitmq.enabled }}
  RABBITMQ_URL: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ include "action-agent.fullname" . }}-rabbitmq:{{ .Values.rabbitmq.service.port }}"
  {{- else }}
  RABBITMQ_URL: "{{ .Values.config.externalRabbitmqUrl }}"
  {{- end }}
  
  {{- if .Values.elasticsearch.enabled }}
  ELASTICSEARCH_URL: "http://{{ include "action-agent.fullname" . }}-elasticsearch:{{ .Values.elasticsearch.service.port }}"
  {{- else }}
  ELASTICSEARCH_URL: "{{ .Values.config.externalElasticsearchUrl }}"
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "action-agent.fullname" . }}-email-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  EMAIL_USERNAME: {{ .Values.config.email.username | quote }}
  EMAIL_PASSWORD: {{ .Values.config.email.password | quote }}

{{- end }}
