{{- if eq .Values.secretProvider "azure" }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.apiGateway }}
  namespace: {{ .Values.global.namespace }}
spec:
  backendType: azureKeyVault
  azureKeyVault:
    tenantId: {{ .Values.azureKeyVault.tenantId }}
    vaultUrl: https://{{ .Values.azureKeyVault.vaultName }}.vault.azure.net
  data:
    - key: apiGateway/HTTPS_PORT
      name: HTTPS_PORT
    - key: apiGateway/SSL_KEY_PATH
      name: SSL_KEY_PATH
    # …and so on for each env var you need
{{- end }}
