{{- if eq .Values.secretProvider "azure" }}
{{- range .Values.externalSecrets }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  backendType: azureKeyVault
  azureKeyVault:
    tenantId: {{ $.Values.azureKeyVault.tenantId }}
    vaultUrl: https://{{ $.Values.azureKeyVault.vaultName }}.vault.azure.net
  data:
{{- range .data }}
    - key: {{ .key }}
      name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
