{{- if eq .Values.secretProvider "azure" }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "action-agent.secretName" (dict "root" . "name" .Values.secrets.apiGateway) }}
  namespace: {{ .Values.global.namespace }}
spec:
  backendType: azureKeyVault
  azureKeyVault:
    tenantId: {{ .Values.azureKeyVault.tenantId }}
    vaultUrl: https://{{ .Values.azureKeyVault.vaultName }}.vault.azure.net
  data:
    - key: apiGateway-PORT
      name: PORT
{{- end }}
