{{- if eq .Values.secretProvider "local" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "action-agent.secretName" (dict "root" . "name" .Values.secrets.apiGateway) }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  PORT: "{{ .Values.apiGateway.service.port }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "action-agent.secretName" (dict "root" . "name" .Values.secrets.userService) }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  MONGO_URI: "mongodb://{{ .Values.userService.database.username }}:{{ .Values.userService.database.password }}@{{ include "action-agent.fullname" . }}-mongo:27017/{{ .Values.userService.database.name }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "action-agent.secretName" (dict "root" . "name" .Values.secrets.aiService) }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  POSTGRES_URI: "postgresql://{{ .Values.aiService.database.username }}:{{ .Values.aiService.database.password }}@{{ include "action-agent.fullname" . }}-postgres:5432/{{ .Values.aiService.database.name }}"
{{- end }}
