{{- if eq .Values.secretProvider "local" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.apiGateway }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
{{- with index .Values.localSecrets .Values.secrets.apiGateway }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}