{{- if eq .Values.secretProvider "local" }}
{{- range $name, $data := .Values.localSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
type: Opaque
stringData:
{{ toYaml $data | indent 2 }}
{{- end }}
{{- end }}
