# Default values for redis
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "redisdev"
fullnameOverride: "redisdev"

image:
  repository: redis
  tag: 7-alpine
  pullPolicy: Always

service:
  type: ClusterIP
  port: 6379

persistence:
  enabled: false
  storageClass: "azurefile"
  skuName: "Standard_LRS"
  accessMode: ReadWriteOnce
  size: 1Gi

redis:
  password: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
