# Default values for userservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 0

image:
  repository: myaagent.azurecr.io/userservice
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: BuildID

imagePullSecrets:
  - name: regcred
nameOverride: "userservice"
fullnameOverride: "userservice"

env:
  secrets:
    name: env-secret
    secret:
      mongodbconnectionstring: mongodbconnectionstring
      jwtsecret: jwtsecret
      emailusername: emailusername
      emailpassword: emailpassword
      googleappclientsecret: googleappclientsecret
      facebookappclientsecret: facebookappclientsecret

service:
  type: ClusterIP
  port: 15100
  targetport: 15100

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: "10m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "300Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
