# Default values for qdrant
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "qdrant"
fullnameOverride: "qdrant"

image:
  repository: "qdrant/qdrant"
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6333
  grpcPort: 6334

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 2Gi

qdrant:
  enableAuth: false
  apiKeySecretName: env-secret
  apiKeySecretKey: qdrantapikey

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
