apiVersion: v1
kind: Service
metadata:
  name: {{ include "extensionservice.fullname" . }}
  labels:
    {{- include "extensionservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
  selector:
    {{- include "extensionservice.selectorLabels" . | nindent 4 }}
