{{- if .Values.autoscaling.enabled }}
{{- range $service := list "api-gateway" "user-service" "ai-service" "extension-service" }}
{{- $serviceConfig := index $.Values.services $service }}
{{- if $serviceConfig.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "action-agent.fullname" $ }}-{{ $service }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "action-agent.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "action-agent.fullname" $ }}-{{ $service }}
  minReplicas: {{ $.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.autoscaling.maxReplicas }}
  metrics:
    {{- if $.Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $.Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- with $.Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
