name: 'Notify Discord'
description: 'Send notifications to Discord about the build or deploy status.'
inputs:
  webhook_url:
    description: 'Discord Webhook URL'
    required: true
  service:
    description: 'The name of the service'
    required: true
  image:
    description: 'The Docker image and tag (e.g., actionagent.azurecr.io/ai-service:dev)'
    required: true
  branch:
    description: 'The branch name from which the action was triggered'
    required: true
  commit_message:
    description: 'The last commit message'
    required: true
  triggered_by:
    description: 'The GitHub user who triggered the action'
    required: true
  time:
    description: 'Timestamp for when the action was triggered'
    required: true
  action:
    description: 'The type of action (BUILD or DEPLOY)'
    required: true
runs:
  using: 'bash'
  steps:
    - name: Send notification to Discord
      run: |
        curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"**✅ [${{ inputs.action }} [${{ inputs.service }}] SUCCESS]**\\n- **Action:** \`${{ inputs.action }}\`\\n- **Service:** \`${{ inputs.service }}\`\\n- **Image:** \`${{ inputs.image }}\`\\n- **Branch:** \`${{ inputs.branch }}\`\\n- **Commit Message:** \`${{ inputs.commit_message }}\`\\n- **Triggered by:** \`${{ inputs.triggered_by }}\`\\n- **Time:** \`${{ inputs.time }}\`\"}" \
          ${{ inputs.webhook_url }}
