{{- if and .Values.persistence.enabled .Values.persistence.createStorageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.storageClass }}
provisioner: kubernetes.io/azure-file
parameters:
  skuName: {{ .Values.persistence.skuName }}
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
{{- end }}
