name: AI Service CI/CD
description: CI/CD pipeline for AI Service

on:
  workflow_dispatch:
    inputs:
      build_and_push_stg:
        description: 'Run Build & Push for Staging'
        required: false
        default: false
        type: boolean
      deploy_stg:
        description: 'Run Deploy for Staging'
        required: false
        default: false
        type: boolean
      build_and_push_prod:
        description: 'Run Build & Push for Production'
        required: false
        default: false
        type: boolean
      deploy_prod:
        description: 'Run Deploy for Production'
        required: false
        default: false
        type: boolean

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      commit_info: ${{ steps.set_commit_info.outputs.commit_info }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set commit message and hash
        id: set_commit_info
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMIT_INFO="$COMMIT_HASH - $COMMIT_MSG"

          echo "commit_info<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_INFO" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build_and_push_stg:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_and_push_stg == 'true' }}
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build & Push for Staging
        uses: ./.github/actions/docker-build-push
        with:
          acr_username: ${{ secrets.ACR_USERNAME }}
          acr_password: ${{ secrets.ACR_PASSWORD }}
          image_name: 'ai-service'
          tag: 'stg'
          folder: './ai-service'

      - name: Send notification to Discord (Build Staging)
        uses: ./.github/actions/notify-discord
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          service: 'ai-service'
          image: 'actionagent.azurecr.io/ai-service:${{ env.STG_TAG }}'
          branch: '${{ github.ref_name }}'
          commit_message: '${{ needs.setup.outputs.commit_info }}'
          triggered_by: ${{ github.actor }}
          time: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          action: 'BUILD'

  deploy_stg:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy_stg == 'true' }}
    needs: [setup, build_and_push_stg]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy AI Service to Staging
        uses: ./.github/actions/deploy
        with:
          ssh_host: ${{ secrets.STG_SSH_HOST }}
          ssh_user: ${{ secrets.STG_SSH_USER }}
          ssh_key: ${{ secrets.STG_SSH_KEY }}
          service: 'ai-service'

      - name: Send notification to Discord (Deploy Staging)
        uses: ./.github/actions/notify-discord
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          service: 'ai-service'
          image: 'actionagent.azurecr.io/ai-service:${{ env.STG_TAG }}'
          branch: '${{ github.ref_name }}'
          commit_message: '${{ needs.setup.outputs.commit_info }}'
          triggered_by: ${{ github.actor }}
          time: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          action: 'DEPLOY'

  build_and_push_prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_and_push_prod == 'true' }}
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Docker Build & Push for Production
        uses: ./.github/actions/docker-build-push
        with:
          acr_username: ${{ secrets.ACR_USERNAME }}
          acr_password: ${{ secrets.ACR_PASSWORD }}
          image_name: 'ai-service'
          tag: 'prod'
          folder: './ai-service'

      - name: Send notification to Discord (Build Production)
        uses: ./.github/actions/notify-discord
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          service: 'ai-service'
          image: 'actionagent.azurecr.io/ai-service:${{ env.PROD_TAG }}'
          branch: '${{ github.ref_name }}'
          commit_message: '${{ needs.setup.outputs.commit_info }}'
          triggered_by: ${{ github.actor }}
          time: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          action: 'BUILD'

  deploy_prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy_prod == 'true' }}
    needs: [setup, build_and_push_prod]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Deploy AI Service to Production
      #   uses: ./.github/actions/deploy
      #   with:
      #     environment: ${{ env.PROD_TAG }}
      #     deploy_command: 'kubectl apply -f deployment.yaml'

      - name: Send notification to Discord (Deploy Production)
        uses: ./.github/actions/notify-discord
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          service: 'ai-service'
          image: 'actionagent.azurecr.io/ai-service:${{ env.PROD_TAG }}'
          branch: '${{ github.ref_name }}'
          commit_message: '${{ needs.setup.outputs.commit_info }}'
          triggered_by: ${{ github.actor }}
          time: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          action: 'DEPLOY'
