name: Trigger auto deployment for user-service

on:
  push:
    branches: [deployment-container-azure]
    paths:
      - "user-service/**" # Chỉ CI/CD khi có thay đổi trong user-service
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.USERSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.USERSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.USERSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./user-service/Dockerfile # Chỉ định Dockerfile của user-service
          registryUrl: registry0001.azurecr.io
          registryUsername: ${{ secrets.USERSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.USERSERVICE_REGISTRY_PASSWORD }}
          containerAppName: user-service
          resourceGroup: DATN-RAG
          imageToBuild: registry0001.azurecr.io/user-service:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: user-service
          resourceGroup: DATN-RAG
          imageToDeploy: registry0001.azurecr.io/user-service:${{ github.sha }}
