name: CI/CD for Azure Container Apps

on:
  push:
    branches:
      - deployment-container-azure # Chạy CI/CD khi push lên nhánh main
  workflow_dispatch: # Cho phép chạy thủ công từ GitHub Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry (ACR)
        run: |
          az acr login --name registry0001.azurecr.io

      # Build và push user-service
      - name: Build and push user-service image
        run: |
          docker build -t registry0001.azurecr.io/user-service:${{ github.sha }} -t registry0001.azurecr.io/user-service:latest ./user-service
          docker push registry0001.azurecr.io/user-service:${{ github.sha }}
          docker push registry0001.azurecr.io/user-service:latest

      # Build và push api-gateway
      - name: Build and push api-gateway image
        run: |
          docker build -t registry0001.azurecr.io/api-gateway:${{ github.sha }} -t registry0001.azurecr.io/api-gateway:latest ./api-gateway
          docker push registry0001.azurecr.io/api-gateway:${{ github.sha }}
          docker push registry0001.azurecr.io/api-gateway:latest

      # Deploy user-service lên Azure Container Apps
      - name: Deploy user-service to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: user-service
          resourceGroup: DATN-RAG
          registryUrl: registry0001.azurecr.io
          imageToBuild: registry0001.azurecr.io/user-service:latest

      # Deploy api-gateway lên Azure Container Apps
      - name: Deploy api-gateway to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: api-gateway
          resourceGroup: DATN-RAG
          registryUrl: registry0001.azurecr.io
          imageToBuild: registry0001.azurecr.io/api-gateway:latest
