export const ACTION_BLACKLIST: string[] = [
  "False",
  "None",
  "True",
  "and",
  "as",
  "assert",
  "async",
  "await",
  "break",
  "class",
  "continue",
  "def",
  "del",
  "elif",
  "else",
  "except",
  "finally",
  "for",
  "from",
  "global",
  "if",
  "import",
  "in",
  "is",
  "lambda",
  "nonlocal",
  "not",
  "or",
  "pass",
  "raise",
  "return",
  "try",
  "while",
  "with",
  "yield",
];

export const ACTION_BLACKLIST_QUERY: Object = {};
ACTION_BLACKLIST.forEach(blacklistedName => {
  ACTION_BLACKLIST_QUERY[`parameters.properties.${blacklistedName}`] = { $exists: true };
});